<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RentadoAsignadoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $asignados = [
            ['asignado' => 'Adel Mahomud'],
            ['asignado' => 'Alejandra Bances'],
            ['asignado' => 'Alejandra Carranza'],
            ['asignado' => 'Alejandra Guzman'],
            ['asignado' => 'Alejandra Jimenez'],
            ['asignado' => 'Alejandra Saenz'],
            ['asignado' => 'Alejandra Trujillo'],
            ['asignado' => 'Alexander Gonzalez'],
            ['asignado' => 'Ana guerra'],
            ['asignado' => 'Ana María Triana Acosta'],
            ['asignado' => 'Andrea Bejarano'],
            ['asignado' => 'Andres Buitrago'],
            ['asignado' => 'Andres Melo'],
            ['asignado' => 'Andres Rubiano'],
            ['asignado' => 'Andres Zarote'],
            ['asignado' => 'Angel Medina'],
            ['asignado' => 'Angela Hernandez'],
            ['asignado' => 'Angelica Herran'],
            ['asignado' => 'Angelica Tello'],
            ['asignado' => 'Angie Cruz'],
            ['asignado' => 'Astrid Rodriguez'],
            ['asignado' => 'Brandon Lara'],
            ['asignado' => 'Brayan Salazar'],
            ['asignado' => 'Camilo Berdugo'],
            ['asignado' => 'Camilo Bornachera'],
            ['asignado' => 'Carlos Rojas'],
            ['asignado' => 'Carlos Serna'],
            ['asignado' => 'Carlos Turriago'],
            ['asignado' => 'Caterin Velasquez'],
            ['asignado' => 'Cristian Martinez'],
            ['asignado' => 'Cristina Martinez'],
            ['asignado' => 'Daniel Alexis Fernández Becerra'],
            ['asignado' => 'Daniel Fernando Hernandez Suarez'],
            ['asignado' => 'Daniela Jimenez'],
            ['asignado' => 'Daniela Mejia'],
            ['asignado' => 'Dasuly Giraldo'],
            ['asignado' => 'David Cubides Deantonio'],
            ['asignado' => 'Diana Cardozo'],
            ['asignado' => 'Didier Castillo'],
            ['asignado' => 'Diego Caro'],
            ['asignado' => 'Edgar Vargas'],
            ['asignado' => 'Edna Alarcon'],
            ['asignado' => 'Edward Fabian Tapiero Gomez'],
            ['asignado' => 'Eliana Robayo'],
            ['asignado' => 'Erick Vacca'],
            ['asignado' => 'Eryk Vacca'],
            ['asignado' => 'Estefani Canelones'],
            ['asignado' => 'Estefania López González'],
            ['asignado' => 'Fernanda Martinez'],
            ['asignado' => 'Fernando Trujillo'],
            ['asignado' => 'FONPAZ'],
            ['asignado' => 'Gabriel Romero'],
            ['asignado' => 'Geraldine Martinez'],
            ['asignado' => 'Gerardo Augusto Arce Arias'],
            ['asignado' => 'Gina Pedraza'],
            ['asignado' => 'Graciela Monroy Calvo'],
            ['asignado' => 'Hailyn Rodriguez'],
            ['asignado' => 'Harold Yepes'],
            ['asignado' => 'Hernan Mauricio Marquez'],
            ['asignado' => 'Hernando Rios'],
            ['asignado' => 'Indira Sauliz'],
            ['asignado' => 'Ivan Jerez'],
            ['asignado' => 'Ivan Murcia'],
            ['asignado' => 'Ivonne Alejandra Brun Basilio'],
            ['asignado' => 'Jaime Andres Guevara Garavito'],
            ['asignado' => 'Jairo Rodriguez'],
            ['asignado' => 'jefferson jimenez'],
            ['asignado' => 'Jeison Ariza'],
            ['asignado' => 'Jenny Niño'],
            ['asignado' => 'Jessica Basallo'],
            ['asignado' => 'Jessica Gaitan'],
            ['asignado' => 'Jesus Vergara'],
            ['asignado' => 'Jhoan Montealegre'],
            ['asignado' => 'Jhonatan Martinez'],
            ['asignado' => 'Johanna Moreno'],
            ['asignado' => 'Johanna Russi'],
            ['asignado' => 'John Calderon'],
            ['asignado' => 'John Rueda'],
            ['asignado' => 'jorge mogollon'],
            ['asignado' => 'jose alexander vargas'],
            ['asignado' => 'Jose Carlo Echeverri Gil'],
            ['asignado' => 'Jose Garcia-diadema pc com'],
            ['asignado' => 'Jose Lopez'],
            ['asignado' => 'Jose Mario Mier Rivera'],
            ['asignado' => 'Juan Carlos Alvarez'],
            ['asignado' => 'Juan David Chavarro Plazas'],
            ['asignado' => 'July Gordillo'],
            ['asignado' => 'Justine Pulido'],
            ['asignado' => 'Karen Ardila'],
            ['asignado' => 'Karin Fuenmayor-diadema pc com'],
            ['asignado' => 'Katherine Amanda Medina Araujo'],
            ['asignado' => 'Katherine Medina'],
            ['asignado' => 'Kevin Guerrero'],
            ['asignado' => 'Kevin Marquez'],
            ['asignado' => 'Kimberly Zambrano'],
            ['asignado' => 'Laura Daniela Cardona Saldarriaga'],
            ['asignado' => 'Laura Izquierdo'],
            ['asignado' => 'Laura Juliana Galvis Vargas'],
            ['asignado' => 'Laura Moreno'],
            ['asignado' => 'Laura Taborda'],
            ['asignado' => 'Leder Andres Martinez Castellon'],
            ['asignado' => 'Leidy Bolivar'],
            ['asignado' => 'Leidy Leon'],
            ['asignado' => 'Los equipos se le entregaron a Claudia Aldana'],
            ['asignado' => 'Luis Bejarano'],
            ['asignado' => 'Luis Hernandez'],
            ['asignado' => 'Luis Pacheco'],
            ['asignado' => 'Luis Samaca'],
            ['asignado' => 'Luis Venegas'],
            ['asignado' => 'Luisa Fernanda Ramirez'],
            ['asignado' => 'Luz Hernandez'],
            ['asignado' => 'Marcela Beltran'],
            ['asignado' => 'María Alejandra Ramírez Zambrano'],
            ['asignado' => 'Maria Bargallo'],
            ['asignado' => 'Maria Velez'],
            ['asignado' => 'Mariana Londoño Bolivar'],
            ['asignado' => 'Michael Santa'],
            ['asignado' => 'Monica Parra'],
            ['asignado' => 'Nanlel Gonzalez'],
            ['asignado' => 'nathalia montenegro'],
            ['asignado' => 'Nestor Cambindo'],
            ['asignado' => 'Nicol Franco'],
            ['asignado' => 'Oscar Infante'],
            ['asignado' => 'Oscar Sosa'],
            ['asignado' => 'Oscar Velazquez'],
            ['asignado' => 'Oswaldo Paez'],
            ['asignado' => 'Paola Arrubla Sanchez'],
            ['asignado' => 'Paola Barbosa'],
            ['asignado' => 'Paula Garzon'],
            ['asignado' => 'Paula Rendon'],
            ['asignado' => 'Rama Judicial'],
            ['asignado' => 'Richard Valderrama'],
            ['asignado' => 'Sandra Molano'],
            ['asignado' => 'Sandra Quiñonez'],
            ['asignado' => 'Santiago Gonzalez Ruge'],
            ['asignado' => 'Sneider Cortes'],
            ['asignado' => 'Sofia Ortega Martinez'],
            ['asignado' => 'Stefania Piedrahita'],
            ['asignado' => 'Steven Robledo'],
            ['asignado' => 'Tatiana Oyola'],
            ['asignado' => 'Tatiana Rodriguez'],
            ['asignado' => 'Valeria Garcia'],
            ['asignado' => 'Vilmary Lopez'],
            ['asignado' => 'Viviana Vanegas'],
            ['asignado' => 'Vladimir Alexander Silva Frias'],
            ['asignado' => 'Wilfer Beltran'],
            ['asignado' => 'Yiced Baracaldo Casas'],
            ['asignado' => 'Yina Ruiz'],
            ['asignado' => 'Yulieth Parra'],
            ['asignado' => 'Jose David Alfonso Robayo'],
            ['asignado' => 'Vanessa Batero Ladino'],
            ['asignado' => 'N/A'],
        ];
        foreach ($asignados as $item) {
            DB::table('rentado_asignados')->insert([
                'asignado' => $item['asignado'],
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ]);
        }
    }
}
