<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RetiroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $retiros = [
            ['cargo' => 'Agente Soporte','usuario' => 'Laura Izquierdo','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Agente Soporte','usuario' => 'Wilfer Beltran','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Agente Soporte','usuario' => 'Karen Ardila','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Agente Soporte','usuario' => 'Alejandra Guzman','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Lider de WorkForce','usuario' => 'Diego Oliveros','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Agente','usuario' => 'Tatiana Oyola','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Analista de información','usuario' => 'Angelica Herran','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Analista en Gestión documental','usuario' => 'Juan Alvarez','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Analista de requerimientos','usuario' => 'Luis Buitrago','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Agente de soporte','usuario' => 'Nanlel Gonzalez','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Agente de soporte','usuario' => 'Andrés Julian Zarate','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador .net','usuario' => 'Daniel Aguilar','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Scrum Master','usuario' => 'Andrei Luna','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Planeer Operations','usuario' => 'Juan Gantiva','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'DataMarshall ','usuario' => 'Nestor Eduardo Cambindo','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Diseñadora','usuario' => 'Laura Poveda','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Community Manager','usuario' => 'Maria Quintero','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Analista de Requerimientos y Mejora Continua','usuario' => 'Gabriel Romero','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Realizador Audiovisual','usuario' => 'Andres Andrade','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Agente de soporte','usuario' => 'Ángela constanza Hernandez López','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Diseñador UX','usuario' => 'Juliett Riveros','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Gerente de Proyectos','usuario' => 'Wilson Molina','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Realizador Audiovisual','usuario' => 'Juan Ramon Baquero Suarez','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador front End','usuario' => 'Benis Carrillo','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Analistafuncional','usuario' => 'Gina Paola Pedraza','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Ingeniera Senior de requerimientos','usuario' => 'Cecilia Mattar','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Abogada','usuario' => 'Maricela Ines Castro Bonilla','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Arquitecto de infraestructura','usuario' => 'Renato Yepes','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Especialista infraestructura','usuario' => 'Sebastian Ordoñez','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Abogado Junior ','usuario' => 'Gabriela Salcedo ','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Developer','usuario' => 'Mauricio ballesteros','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Community Manager','usuario' => 'Sebastian Sastoque','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Analista de infraestructura Cloud','usuario' => 'Cristian Gomez','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador Junior','usuario' => 'Jhon Acosta','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador fullstack','usuario' => 'Daniel Hernandez','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Profesional en seleccion','usuario' => 'Jorge Andrés Rojas Paez','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Agente Soporte','usuario' => 'Katherine Medina','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Hidrologo','usuario' => 'Jairo Alexander Castro','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Analista de requerimientos','usuario' => 'Maria Velez','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Lider Copy','usuario' => 'Nicolas Torres','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Productor Audiovisual','usuario' => 'Juan Sebastian Beltran Diaz','ticket' => 'N/A','centro_costos' => '293 - PROYECTO INTERNO EL DORADO'],
            ['cargo' => 'Community Manager','usuario' => 'Mayra Daniela Arboleda Trejos','ticket' => 'N/A','centro_costos' => '293 - PROYECTO INTERNO EL DORADO'],
            ['cargo' => 'Community Manager','usuario' => 'Gabriela Pinzon','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Realizador audiovisual','usuario' => 'Sebastian Coronado','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'camarografo','usuario' => 'Ivan Hernandez','ticket' => 'N/A','centro_costos' => '293 - PROYECTO INTERNO EL DORADO'],
            ['cargo' => 'Realizador Audiovisual','usuario' => 'Juan David Estrada Céspedes','ticket' => 'N/A','centro_costos' => '293 - PROYECTO INTERNO EL DORADO'],
            ['cargo' => 'Asistente Diseño','usuario' => 'Eliana Ibañez','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Gerente de proyectos','usuario' => 'Alexander Garcia','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Agente Soporte','usuario' => 'Andres Melo','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Ingeniero constructor de contenidos Modulos Capacitación','usuario' => 'Pedro Perez','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador Intermedio','usuario' => 'Juan Sebastian Rodriguez','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'camarografo','usuario' => 'Ivan Hernandez','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Analista de Marketing','usuario' => 'Luis Torres','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Profesional Audiovisual','usuario' => 'Andres Villamarin','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Agente de soporte','usuario' => 'Indira Sauliz','ticket' => 'N/A','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Analista QA','usuario' => 'Alejandra Rivera','ticket' => 'N/A','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Diseñador Grafico','usuario' => 'Juan Castrillon','ticket' => 'N/A','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Ingeniera de requerimientos','usuario' => 'Cynthia Parra','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Diseñadora','usuario' => 'Anyi Arboleda','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Analista de requerimientos','usuario' => 'Diana Rocio Cerquera','ticket' => 'N/A','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Web Máster','usuario' => 'Humberto Lopez','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Gerente de proyecto','usuario' => 'Herney Ortega','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Gerente de proyectos','usuario' => 'Yusmari Rivas','ticket' => 'N/A','centro_costos' => '313 - PROYECTO FINDETER - ARCHIVO'],
            ['cargo' => 'Diseñador gráfico','usuario' => 'Otoniel Penates','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Analista de Informacion','usuario' => 'Ricardo Ospina','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Analista de información','usuario' => 'Valentina Estrada','ticket' => 'N/A','centro_costos' => '298 - UNIVERSIDAD DE PEREIRA'],
            ['cargo' => 'Agente de soporte','usuario' => 'Angela Hernandez','ticket' => 'N/A','centro_costos' => '298 - UNIVERSIDAD DE PEREIRA'],
            ['cargo' => 'Analista de datos','usuario' => 'Daniel Caicedo Narvaez','ticket' => 'N/A','centro_costos' => '298 - UNIVERSIDAD DE PEREIRA'],
            ['cargo' => 'Agente de soporte','usuario' => 'Kevin Guerrero','ticket' => 'N/A','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Agente de soporte','usuario' => 'Monica Parra','ticket' => 'N/A','centro_costos' => '298 - UNIVERSIDAD DE PEREIRA'],
            ['cargo' => 'Agente de soporte','usuario' => 'Laura Izquierdo','ticket' => 'N/A','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Agente de soporte','usuario' => 'Carlos Rojas','ticket' => 'N/A','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Ingeniero Semi Senior','usuario' => 'Leonel Gomez','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador .net','usuario' => 'Darwin Aguiño','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Asesor de apropiación digital - Escuela TIC familia','usuario' => 'Alexandra Gomez','ticket' => 'N/A','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Asesor de apropiación digital - Escuela TIC familia','usuario' => 'Julisa Lopez','ticket' => 'N/A','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Asesor de apropiación digital - Escuela TIC familia','usuario' => 'Alba Ordoñez Pantoja ','ticket' => 'N/A','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Agente de soporte','usuario' => 'Alejandra Carranza','ticket' => 'N/A','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Agente de soporte','usuario' => 'Brayan Salazar','ticket' => 'N/A','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'agente de soporte','usuario' => 'jefferson jimenez','ticket' => 'N/A','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Agente de soporte','usuario' => 'Jenny Niño','ticket' => 'N/A','centro_costos' => '298 - UNIVERSIDAD DE PEREIRA'],
            ['cargo' => 'formadora','usuario' => 'nathalia montenegro','ticket' => 'N/A','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Profesional de apoyo Programa primer empleo','usuario' => 'Maria Gomez','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Analista de informacion','usuario' => 'Katherine medina','ticket' => 'N/A','centro_costos' => '298 - UNIVERSIDAD DE PEREIRA'],
            ['cargo' => 'Contratación Real time Analist','usuario' => 'Jefferson Patarroyo Torres','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Analista evidencia Escuela TIC','usuario' => 'Sonia Rodriguez','ticket' => 'N/A','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Analista de Proyectos','usuario' => 'Rafael Lopez','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Ingeniero Capacitador y lider construcción de contenidos Capacitación','usuario' => 'Eugenio Bernal','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Lider Operativo','usuario' => 'Claudia Liliana Pabon Calderon','ticket' => 'N/A','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Diseñador Instruccional y estructural','usuario' => 'Claudia Puentes','ticket' => 'N/A','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Diseñadora','usuario' => 'alexandra Parrales','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Lider Asesores','usuario' => ' Danilo Santiago Vargas jiménez','ticket' => 'N/A','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Asesor de apropiación digital - Escuela TIC familia','usuario' => 'Susana Hernandez','ticket' => 'N/A','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Especialista en seguridad informática','usuario' => 'Dario Giraldo','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Gerente general','usuario' => 'Jhon Calderon','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador','usuario' => 'Fredy Tovar','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Analista de pruebas Senior','usuario' => 'Carlos Turriago','ticket' => 'N/A','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Ingeniero de infraestructura cloud','usuario' => 'Hector Heredia','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Analista de infraestructura','usuario' => 'Jorge Viloria','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Analista de requerimientos','usuario' => 'Lesley Mesa','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Analista de infraestructura cloud','usuario' => 'Eduardo Sotelo','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Lider Comercial','usuario' => 'Gustavo Ospino','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador intermedio','usuario' => 'Jose Rivera','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Lider De Infraestructura','usuario' => 'Fabian Martinez','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Ingeniero Cloud','usuario' => 'Arquimedes Cardoso','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Director Audiovisual','usuario' => 'Juan Pardo','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Realizador Audiovisual','usuario' => 'Angie Ortega','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Asistente de operaciones','usuario' => 'Daniel rodirguez','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Analista de requerimientos','usuario' => 'Luz Adriana Hernandez','ticket' => 'N/A','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Desarrollador de QA Med','usuario' => 'Lady Arias','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Desarrollador intermedio','usuario' => 'Joel Suarez','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Gerente de proyectos','usuario' => 'Sandra Ruiz','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Copy','usuario' => 'Adriana Lopez','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Asesor','usuario' => 'Mayerly López','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asistente de Soporte','usuario' => 'Hector Lopez','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Agente Contac Center','usuario' => 'Natalia Bolaños','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asesor ','usuario' => 'Camilo Beltran ','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Capacitador y Lider metodología de construcción','usuario' => 'William Forero','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Agente de soporte','usuario' => 'Julieth Parra','ticket' => 'N/A','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Agente de soporte','usuario' => 'Diego Rueda','ticket' => 'N/A','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Asesor','usuario' => 'Maria Andrea Medina','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asesor','usuario' => 'Nicol Conde','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asesor','usuario' => 'Karen Ardila','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Desarrollador intermedio','usuario' => 'Miguel Vega','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Coordinacion','usuario' => 'Ray Miller','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Arquitecto','usuario' => 'Daniel Alexis Fernández Becerra','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Agente','usuario' => 'Jessica Acosta','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Desarrollador .net','usuario' => 'Boris Gonzalez','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Diseñadora Gráfica','usuario' => 'Lady Montoya','ticket' => 'N/A','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Auxiliar de Soporte','usuario' => 'Leidy Lopez','ticket' => 'N/A','centro_costos' => '295-3 - REGISTRADURIA TPS (Jurados, testigos y delegados)'],
            ['cargo' => 'Diseñadora','usuario' => 'Natalia Garzon','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Asistente de soporte','usuario' => 'Jonathan Gutierrez','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Analista de pruebas','usuario' => 'Johan Montero','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Analista de pruebas Senior','usuario' => 'Johanna Moreno','ticket' => 'N/A','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Analista de soporte Marketing','usuario' => 'Katherine Castañeda','ticket' => 'N/A','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tecnico en Analisis de Datos','usuario' => 'Daniel Clavijo','ticket' => 'N/A','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Tutor','usuario' => 'Laura Carrillo','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Angelica Guzman','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Gloria Arango','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Monica Maldonado','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Oscar Morales','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Samira Panroja','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Miller Murcia','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Andres Velazco','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Agente','usuario' => 'Valentina Rojas','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asesor','usuario' => 'Claudia Rodriguez','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Arquitecto Software','usuario' => 'Karen Cervantes','ticket' => 'N/A','centro_costos' => '321 - PROYECTO CPE MONITOREO Y EVALUACIÓN FASE II'],
            ['cargo' => 'Tutor','usuario' => 'Miguel Viasus','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Kevin Jimenez','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Hernan Velasquez','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Agente','usuario' => 'Sofia Zipacon','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Analista','usuario' => 'Maria Sierra','ticket' => 'N/A','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Asistente Contratacion publica','usuario' => 'Nocholls Figueredo','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Profesional Operativo','usuario' => 'Manuel Hastamorir','ticket' => 'N/A','centro_costos' => '321 - PROYECTO CPE MONITOREO Y EVALUACIÓN FASE II'],
            ['cargo' => 'Auxiliar de Soporte','usuario' => 'Santiago Hernández','ticket' => 'N/A','centro_costos' => '295-3 - REGISTRADURIA TPS (Jurados, testigos y delegados)'],
            ['cargo' => 'Desarrollador ','usuario' => 'Diego Camelo','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador','usuario' => 'Jesus Leon','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Ingeniero Cloud','usuario' => 'Joaquin Garces','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Auxiliar de Soporte','usuario' => 'Jineth Vargas','ticket' => 'N/A','centro_costos' => '295-3 - REGISTRADURIA TPS (Jurados, testigos y delegados)'],
            ['cargo' => 'Analista funcional de requerimientos','usuario' => 'Martha Robledo','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Diseñadora','usuario' => 'Anyi Arboleda','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Gerente de Proyectos','usuario' => 'Johan Piñeres','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Consultor de Gestion','usuario' => 'Ruth Daza','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Lider de Data y Gestión','usuario' => 'Nathalia Corredor','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Lider de Proceso Electoral','usuario' => 'Wilson Lasso','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador Java','usuario' => 'David Vanegas','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Ingeniero cloud','usuario' => 'Sebastian Curtidor','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Tutor','usuario' => 'Monica Maldonado','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asesor de apropiación digital - Escuela TIC familia','usuario' => 'Cristobal Parra','ticket' => 'N/A','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Arquitecto de datos','usuario' => 'Holman Garcia','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Consultor GIS','usuario' => 'Manuel Benavides','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Lider Operativo','usuario' => 'Diana Rincon','ticket' => 'N/A','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Lider Operativo','usuario' => 'Paola Rios','ticket' => 'N/A','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Lider de Calidad','usuario' => 'Carolina Herrera','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Consultor en Gestion de Cambio','usuario' => 'Javier Said','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Back Office','usuario' => 'Brayan Salazar','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asesor','usuario' => 'Yannirex Amundaray','ticket' => 'N/A','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asesor','usuario' => 'Dennys Buitrago','ticket' => '9449','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Consultor','usuario' => 'Guillermo Prada','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Gestion Documental','usuario' => 'Karen Duarte','ticket' => '9482','centro_costos' => '313 - PROYECTO FINDETER - ARCHIVO'],
            ['cargo' => 'Realizador Audiovisual','usuario' => 'Sebastian Fajardo','ticket' => '9756','centro_costos' => 'N/A'],
            ['cargo' => 'Formador','usuario' => 'Jorge Mogollon','ticket' => '9439','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Mesa de Ayuda','usuario' => 'Camila Giraldo','ticket' => '9541','centro_costos' => '295-3 - REGISTRADURIA TPS (Jurados, testigos y delegados)'],
            ['cargo' => 'Tutor','usuario' => 'Javier Diaz','ticket' => '9783','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => ' Asistente administrativo y financiero','usuario' => 'Jackeline Ospina Ospina','ticket' => '9086','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Gestor Documental','usuario' => 'Erick Johann Fonseca Perilla','ticket' => '9054','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'soporte correo y medios publicitario','usuario' => 'Gary Garcia','ticket' => '9271','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Asesor de apropiación digital - Escuela TIC familia','usuario' => 'Carlos Andrés Martínez Mendoza','ticket' => '9164','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Asesor de apropiación digital - Escuela TIC familia','usuario' => 'Yeimy Yulieth Hernández Pérez','ticket' => '9160','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Diseñador Instruccional','usuario' => 'Leidy Hurtado','ticket' => '9076','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Diseñador Instruccional','usuario' => 'Luis Amortegui','ticket' => '9079','centro_costos' => '309 - PROYECTO UTP PERIRA FORMACION2022'],
            ['cargo' => 'Agente ','usuario' => 'Steven Sierra','ticket' => '9872','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Directora Financiera','usuario' => 'Maria Esperanza Torres','ticket' => '9972','centro_costos' => 'N/A'],
            ['cargo' => 'datamarshall','usuario' => 'John Palacios','ticket' => '9443','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Desarrollador Senior','usuario' => 'Manuel Montero','ticket' => '7746','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador Intermedio','usuario' => 'Fauce Mocharrafich','ticket' => '8329','centro_costos' => 'N/A'],
            ['cargo' => 'Agente','usuario' => 'Erick Cruz','ticket' => '9877','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Analista de requerimientos','usuario' => 'yiseth lozada','ticket' => '10159','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Asesora Juridica','usuario' => 'Isabel Cristina Vargas Sinisterra','ticket' => '9266','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador PLSQL','usuario' => 'Maria Del Pilar Restrepo','ticket' => '9506','centro_costos' => 'N/A'],
            ['cargo' => 'Gerente de Proyectos','usuario' => 'German David Becerra','ticket' => '9645','centro_costos' => '321 - PROYECTO CPE MONITOREO Y EVALUACIÓN FASE II'],
            ['cargo' => 'Analista de informacion','usuario' => 'Ricardo Ospina','ticket' => '9778','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Yadira Murcia','ticket' => '9781','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Erika Riaño','ticket' => '9829','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asesor','usuario' => 'Lidia Angelica Rojas','ticket' => '9451','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asesor','usuario' => 'Ricardo Romero','ticket' => '10149','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Gerente de Proyectos','usuario' => 'Monica Rey','ticket' => '8881','centro_costos' => 'N/A'],
            ['cargo' => 'Ingeniero Drupal','usuario' => 'Jorge Beduit','ticket' => '6994','centro_costos' => 'N/A'],
            ['cargo' => 'Analista de Calidad','usuario' => 'Oscar Parra','ticket' => '9478','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Analista QA','usuario' => 'Yuly Cortes','ticket' => '10158','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Analista','usuario' => 'Alejandra Trujillo','ticket' => '9988','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Analista de Requerimientos','usuario' => 'Sebastian Fajardo vega','ticket' => '1053','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Líder de implementación','usuario' => 'Luis Bejarano','ticket' => '7677','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador','usuario' => 'Carlos Ricaurte','ticket' => '10209','centro_costos' => '324 - PROYECTO ADRES'],
            ['cargo' => 'Desarrollador Java','usuario' => 'Jairo castrillon','ticket' => '9071','centro_costos' => '286 - ACUEDUCTO (SISTEMA DE INFORMACIÓN HÍDRICO)'],
            ['cargo' => 'Abogada Funcional','usuario' => 'Angelica Rodriguez','ticket' => '9995','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Desarrollador Node JS - React','usuario' => 'Jesus Leon','ticket' => '7038','centro_costos' => '318 - PROYECTO FABRICA DE SOFTWARE 2022-FISCALIA'],
            ['cargo' => 'Analista de informacion','usuario' => 'Nicolás Ramirez','ticket' => '9945','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Analista de informacion','usuario' => 'Paula Ferrin','ticket' => '9780','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Desarrollador Senior','usuario' => 'Gerardo Forero Herrera','ticket' => '3575-5641','centro_costos' => 'N/A'],
            ['cargo' => 'Project Manager','usuario' => 'Silvia Paola Gallego','ticket' => '7695','centro_costos' => 'N/A'],
            ['cargo' => 'Lider Tecnopedagogico','usuario' => 'Napoleon Mendez','ticket' => '9382','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Formador','usuario' => 'Fernanda Sarmiento','ticket' => '10360','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asistente de Talento','usuario' => 'Jessica Ramirez','ticket' => '10133','centro_costos' => 'N/A'],
            ['cargo' => 'Community Manager','usuario' => 'Andrea Castellanos','ticket' => '9859','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Agente','usuario' => 'Paola Mora','ticket' => '9874','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Analista de requerimientos','usuario' => 'Ingrid Garzon','ticket' => '10150','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Documentador','usuario' => 'Jhon Alexander Agudelo Zuluaga','ticket' => '9609','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'BackOffice','usuario' => 'Nathaly Rodriguez','ticket' => '10208','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Arquitecto Software / Formulador','usuario' => 'Enrique Medina','ticket' => '9956','centro_costos' => 'N/A'],
            ['cargo' => 'Gerente De Proyectos','usuario' => 'Norma Perez','ticket' => '7809','centro_costos' => '280 - COMERCIO ELECTRÓNICO - DUBRANDS'],
            ['cargo' => 'Agente','usuario' => 'Luz Gomez','ticket' => '9871','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Agente','usuario' => 'Melissa Aguirre','ticket' => '9873','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tecnólogo en análisis y desarrollo de sistemas de información','usuario' => 'Luis Samaca','ticket' => '7971','centro_costos' => 'N/A'],
            ['cargo' => 'Tecnólogo en análisis y desarrollo de sistemas de información','usuario' => 'Diego Caro','ticket' => '7941','centro_costos' => 'N/A'],
            ['cargo' => 'Analista de Requerimientos JR','usuario' => 'Esmeralda Pava','ticket' => '9740','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Ingeniero Azure','usuario' => 'Renato Yepes','ticket' => '10254','centro_costos' => '321 - PROYECTO CPE MONITOREO Y EVALUACIÓN FASE II'],
            ['cargo' => 'DESARROLLADOR JAVA','usuario' => 'Diego Sanchez','ticket' => '10719','centro_costos' => '303 - PROYECTO 472 CONTRATO N° 239-2021'],
            ['cargo' => 'Tutor','usuario' => 'Heydy Valdes','ticket' => '9834','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Jennifer Acevedo','ticket' => '9838','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asistente de licitaciones','usuario' => 'Julieth Perdomo','ticket' => '10268','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador Angular','usuario' => 'Luis Hernando Sierra','ticket' => '10542','centro_costos' => '318 - PROYECTO FABRICA DE SOFTWARE 2022-FISCALIA'],
            ['cargo' => 'Agente','usuario' => 'Santiago Colorado','ticket' => '9875','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Agente','usuario' => 'Andres Ferran','ticket' => '9867','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asesor','usuario' => 'Lina Pacheco','ticket' => '9665','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asesor','usuario' => 'Brayan Rodriguez','ticket' => '9860','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asesor','usuario' => 'Lina Peña','ticket' => '9446','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asesor','usuario' => 'Angie Carolina Naranjo','ticket' => '9454','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asesor','usuario' => 'Francy Velandia','ticket' => '9664','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asesor','usuario' => 'Julian Valencia','ticket' => '9460','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asesor','usuario' => 'Andrea Ayala','ticket' => '9464','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asesor','usuario' => 'karol Prieto','ticket' => '9459','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asesor','usuario' => 'Fernando Ladino','ticket' => '9447','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asesor','usuario' => 'Erika Mejia','ticket' => '9448','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Daniel Rozo','ticket' => '9798','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'DESARROLLADOR FRONT END','usuario' => 'Francarlos Blanco','ticket' => '10475','centro_costos' => '295-6 PROYECTO REGISTRADURIA'],
            ['cargo' => 'Analista de Marketing','usuario' => 'Dasuly Giraldo Aristizábal','ticket' => '8952','centro_costos' => '298 - UNIVERSIDAD DE PEREIRA'],
            ['cargo' => 'Gerente de Proyectos','usuario' => 'Mabel Palacios','ticket' => '9324','centro_costos' => 'N/A'],
            ['cargo' => 'Analista de Datos','usuario' => 'Julian Prada','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => ' Community Manager','usuario' => 'Jessica Gaitan','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Pasante Sena (Asistente Soporte IT)','usuario' => 'Nicol Galindo','ticket' => '9339','centro_costos' => 'N/A'],
            ['cargo' => 'Tutor','usuario' => 'Nathalia Montenegro','ticket' => '9843','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Contoller','usuario' => 'Judy Perlata','ticket' => '9816','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Arquitecto de Implementacion','usuario' => 'Enrique Gonzalez','ticket' => '10689','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Tutor','usuario' => 'Elmer Amador','ticket' => '9828','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Coordinador de proyectos','usuario' => 'Alam Gonzalez','ticket' => '7996','centro_costos' => 'N/A'],
            ['cargo' => 'Auxiliar Contable','usuario' => 'Liliana Vacca','ticket' => '7847','centro_costos' => 'N/A'],
            ['cargo' => 'DESARROLLADOR JAVA','usuario' => 'Edwin Lopez','ticket' => '10719','centro_costos' => '303 - PROYECTO 472 CONTRATO N° 239-2021'],
            ['cargo' => 'Ingeniero Cloud','usuario' => 'Andres Hernandez','ticket' => '9954','centro_costos' => 'N/A'],
            ['cargo' => 'Realizador Audiovisual','usuario' => 'Daniel Alarcon','ticket' => '9085','centro_costos' => 'N/A'],
            ['cargo' => 'Profesional de requerimientos','usuario' => 'Ivan Moreno','ticket' => '8054','centro_costos' => 'N/A'],
            ['cargo' => 'Ingeniero de Desarrollo','usuario' => 'Carlos Barrero','ticket' => '10628','centro_costos' => '324 - PROYECTO ADRES'],
            ['cargo' => 'Desarrollador intermedio Net','usuario' => 'Sergio Junco','ticket' => '10652','centro_costos' => '321 - PROYECTO CPE MONITOREO Y EVALUACIÓN FASE II'],
            ['cargo' => 'Profesional de requerimientos','usuario' => 'Ivan Moreno','ticket' => '8054','centro_costos' => 'N/A'],
            ['cargo' => 'Ingeniero de Desarrollo Senior','usuario' => 'Juan hernandez','ticket' => '9153','centro_costos' => '303 - PROYECTO 472 CONTRATO N° 239-2021'],
            ['cargo' => 'INGENIERO PREVENTA SENIOR','usuario' => 'Juan Gutierrez','ticket' => '10788','centro_costos' => 'N/A'],
            ['cargo' => 'Profesional Especializado PMO','usuario' => 'Ivan Marin','ticket' => '9975','centro_costos' => 'N/A'],
            ['cargo' => 'Ingeniero cloud','usuario' => 'Eduardo Sotelo ','ticket' => '8923','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador Intermedio ','usuario' => 'Camilo Andres Valle','ticket' => '10344','centro_costos' => '321 - PROYECTO CPE MONITOREO Y EVALUACIÓN FASE II'],
            ['cargo' => ' ANALISTA DE REQUERIMIENTOS','usuario' => 'JOHAN ESTIVEN MONTERO TIQUE','ticket' => '10900','centro_costos' => '342- MINMINAS ORFEO'],
            ['cargo' => 'DESARROLLADOR SEMI SENIOR ORFEO','usuario' => 'Edwin Garibello','ticket' => '10877','centro_costos' => '342- MINMINAS ORFEO'],
            ['cargo' => 'Especialista Seg Informatica','usuario' => 'Yulian Leandro Hernandez Cruz','ticket' => '9705','centro_costos' => 'N/A'],
            ['cargo' => 'Líder técnico','usuario' => 'Gustavo Alzate','ticket' => '8641','centro_costos' => '298 - UNIVERSIDAD DE PEREIRA'],
            ['cargo' => 'lider de INFRAESTRUCTURA','usuario' => 'Luis Perez','ticket' => '3192','centro_costos' => 'N/A'],
            ['cargo' => ' ANALISTA DE DATOS Y MIGRACION','usuario' => 'Maribel Montenegro','ticket' => '10690','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Desarrollador Java','usuario' => 'Leonardo Jose Ruiz Gomez','ticket' => '10821','centro_costos' => '303 - PROYECTO 472 CONTRATO N° 239-2021'],
            ['cargo' => 'Desarrollador Java','usuario' => 'Daniel Felipe Zapata Parra','ticket' => '10924','centro_costos' => '303 - PROYECTO 472 CONTRATO N° 239-2021'],
            ['cargo' => 'Lider Tecnico Orfeo','usuario' => 'Daniel Joaquin Rodriguez Morales','ticket' => '10967','centro_costos' => '342- MINMINAS ORFEO'],
            ['cargo' => 'Analista','usuario' => 'Gabriela Pinzon','ticket' => '9917','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Analista','usuario' => 'Jenny Pineda','ticket' => '9915','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Analista','usuario' => 'Karen Natalia Cuervo','ticket' => '8712','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Analista','usuario' => 'Lorena Rivera','ticket' => '9910','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Analista','usuario' => 'Nicolas Eduardo Cabrera Motta','ticket' => '9945','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Analista','usuario' => 'Nubia Sanchez','ticket' => '9912','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Analista','usuario' => 'Paula Ferrin','ticket' => '9780','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Analista','usuario' => 'Janeth Barbosa','ticket' => '9909','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Analista','usuario' => 'Miguel Borrero','ticket' => '9913','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Analista','usuario' => 'Andres Rubiano','ticket' => '9916','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Analista','usuario' => 'Jessica Malagon','ticket' => '9918','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Analista','usuario' => 'Maria de Los Angeles Guerra Loaiza','ticket' => '9971','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Jorge Parra','ticket' => '10056','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Angela Vargas','ticket' => '10057','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Diana Maya','ticket' => '10059','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Lina Moreno','ticket' => '10060','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Alejandra Triana','ticket' => '10061','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Pedro Sandoval','ticket' => '10062','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Marisol Cortes','ticket' => '10071','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Luz Baraona','ticket' => '10072','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'John Leon','ticket' => '10073','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Daniela Forero','ticket' => '10074','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Edgar Angel','ticket' => '10075','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Sandra Pinzon','ticket' => '10076','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Edwin Grandas','ticket' => '10077','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Yanuary stabilito','ticket' => '10078','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Diana Castaño','ticket' => '10079','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Jenny Porras','ticket' => '10080','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Mayra Carvajal','ticket' => '10081','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Pabla Hernandez','ticket' => '10082','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Dina Almanza','ticket' => '10083','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Maria Claudia Rosero','ticket' => '10084','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Rene Reyes','ticket' => '10085','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Juan Pablo Rodriguez','ticket' => '10086','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Vanesa Escucha','ticket' => '10088','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Monica Gaona','ticket' => '10090','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Marbeen Mosquera','ticket' => '10091','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Jeison Correa','ticket' => '10094','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Liz Hernandez','ticket' => '10095','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Daris Montiel','ticket' => '10096','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Julian Castiblanco','ticket' => '10097','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Julieth Rivera','ticket' => '10098','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Jorge Benavides','ticket' => '10099','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Lizeth Plazas','ticket' => '10100','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Tutor','usuario' => 'Danilo Rincon','ticket' => '10101','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Diana Neira','ticket' => '10102','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Henry Romero','ticket' => '10103','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Maria Castro','ticket' => '10113','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Breiner Cervantes','ticket' => '10106','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Mayerly Parga','ticket' => '10104','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Cesar Orozco','ticket' => '10105','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Jennifer Guiza','ticket' => '10107','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Cesar Muñoz','ticket' => '10109','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Yisel Recalde','ticket' => '10108','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Karen Molinares','ticket' => '10111','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Paola Marin','ticket' => '10110','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Stifanny Martinez','ticket' => '10112','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Laura Leal','ticket' => '10114','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Yeimy yulieth Hernandez','ticket' => '10116','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Natalia Pedraza','ticket' => '10128','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Luis Huerfano ','ticket' => '10115','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Carolina Bello','ticket' => '10117','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Camilo Gonzalez','ticket' => '10119','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Juan Manuel Sanchez','ticket' => '10118','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Carlos Rojas','ticket' => '10120','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Monica Castilla','ticket' => '10130','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Hercen Castro','ticket' => '10121','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Maria Riveros','ticket' => '10124','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Andres Albuja','ticket' => '10122','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Valentina Beltran','ticket' => '10123','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Sebastian Bernal','ticket' => '10125','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Cristian Rojas','ticket' => '10126','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Vanesa Uribe','ticket' => '10127','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Diego Garcia','ticket' => '10129','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Cesar Mosquera','ticket' => '10131','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Tutor','usuario' => 'Mauricio Patiño','ticket' => '10134','centro_costos' => '316 - PROYECTO VENDE DIGITAL CYMETRIA 2022'],
            ['cargo' => 'Lider Tecnopedagogico','usuario' => 'Xiomara Reyes','ticket' => '9383','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Lider Admin y Financiero','usuario' => 'Julian esteban Perdomo Mejia','ticket' => '9551','centro_costos' => '314 - PROYECTO VENDE DIGITAL 2022'],
            ['cargo' => 'Desarrollador Intermedio','usuario' => 'Esneider Ariza','ticket' => '7746','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador Jr','usuario' => 'Jonathan Vargas','ticket' => '9676','centro_costos' => '321 - PROYECTO CPE MONITOREO Y EVALUACIÓN FASE II'],
            ['cargo' => 'Ingeniera de infraestructura cloud','usuario' => 'Shirley saavedra','ticket' => '10883','centro_costos' => 'N/A'],
            ['cargo' => 'Analista de pruebas Senior','usuario' => 'Cesar Andres Pulido Mejia','ticket' => '7914','centro_costos' => 'N/A'],
            ['cargo' => 'Profesional en Auditoria ','usuario' => 'Diego Alejandro Artunduaga Acevedo','ticket' => '11066','centro_costos' => '343- CONTROL INTERNO'],
            ['cargo' => 'Analista de requerimientos','usuario' => 'Maria Alejandra Londoño Feria','ticket' => '10687','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Consultor de Gestion','usuario' => 'David Borrero','ticket' => '9965','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Coordinadora de Eventos','usuario' => 'Adriana Vasquez Martinez','ticket' => '10622','centro_costos' => 'N/A'],
            ['cargo' => 'Lider Tecnico ','usuario' => 'Yan Pier Chirino Aular','ticket' => '10749','centro_costos' => '329 - PROYECTO INTERNO ERP LINKTIC'],
            ['cargo' => 'Gerente de Proyectos','usuario' => 'Rocio Gomez Rojas','ticket' => '10851','centro_costos' => '341- UT ANTICIPACION Y RESULTADOS'],
            ['cargo' => ' Analista de TI.','usuario' => 'Maria Velez','ticket' => '9904','centro_costos' => '307 - PROYECTO CMMI NIVEL 5'],
            ['cargo' => 'DESARROLLADOR NODE JS','usuario' => 'Daniel Lobo','ticket' => '10627','centro_costos' => '318 - PROYECTO FABRICA DE SOFTWARE 2022-FISCALIA'],
            ['cargo' => 'Tecnólogo en análisis y desarrollo de sistemas de información','usuario' => 'Oscar Mauricio Velasquez Botina','ticket' => '7972','centro_costos' => 'N/A'],
            ['cargo' => 'Auxiliar Contable','usuario' => 'Diana Franco','ticket' => '10923','centro_costos' => 'N/A'],
            ['cargo' => 'Desarollador Junior','usuario' => 'Jorman Alejandro Sanchez Gil','ticket' => '9679','centro_costos' => '321 - PROYECTO CPE MONITOREO Y EVALUACIÓN FASE II'],
            ['cargo' => 'Tutor','usuario' => 'Jose Jurado','ticket' => '9784','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Claudia Alarcon','ticket' => '9786','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Lady Figueroa','ticket' => '9771','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Profesional de Operaciones ','usuario' => 'Cesar Anibal Ariza Tacha','ticket' => '9801','centro_costos' => 'N/A'],
            ['cargo' => 'Arquitento de Soluciones','usuario' => 'Elias Reinaldo Gamez Pinilla','ticket' => '9338','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Arquitecto de datos','usuario' => ' Armando Fonseca Vargas','ticket' => '8013','centro_costos' => 'N/A'],
            ['cargo' => 'Especialista en Migración de datos 1','usuario' => 'Mario Fernando Trujillo Amaya','ticket' => '9035','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Experta en digitalizacion y migracion','usuario' => 'Ana Cecilia Redondo Ramirez','ticket' => '11053','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Desarrollador NODEjs-React','usuario' => 'Euclides Rodriguez Gaitán','ticket' => '9511','centro_costos' => 'N/A'],
            ['cargo' => 'Especialista BI','usuario' => 'Sandra Milena Mora Martinez','ticket' => '9669','centro_costos' => '321 - PROYECTO CPE MONITOREO Y EVALUACIÓN FASE II'],
            ['cargo' => 'Desarrolladora QAMED','usuario' => 'Leidy Maribel Arias Jimenez','ticket' => '9349','centro_costos' => '318 - PROYECTO FABRICA DE SOFTWARE 2022-FISCALIA'],
            ['cargo' => 'Realizador Audiovisual','usuario' => 'Omar Felipe Guerrero Herrera','ticket' => '9815','centro_costos' => 'N/A'],
            ['cargo' => 'Desarollador Junior','usuario' => 'Jose Esteban Colorado Montenegro','ticket' => '9678','centro_costos' => '321 - PROYECTO CPE MONITOREO Y EVALUACIÓN FASE II'],
            ['cargo' => 'DESARROLLADOR NODE JS','usuario' => 'Erick Fernando Alarcon Duran','ticket' => '10726','centro_costos' => '318 - PROYECTO FABRICA DE SOFTWARE 2022-FISCALIA'],
            ['cargo' => 'Lider de Infraestructura','usuario' => 'Rodrigo Niampira Romero','ticket' => '9362','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador PHP','usuario' => 'Jorge Lopez','ticket' => '10688','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Implementador COGNOS','usuario' => 'Valeria Gualdron Buendia','ticket' => '9517','centro_costos' => 'N/A'],
            ['cargo' => 'Gerente de Proyectos','usuario' => 'Andres Felipe Rincon Valencia','ticket' => '11112','centro_costos' => '338- Proyecto interno BPM LinkTIC y Filiales'],
            ['cargo' => 'Desarrollador Java Junior','usuario' => 'Diego Andres Berdugo Castro','ticket' => '10957','centro_costos' => '339- PROLINKTIC'],
            ['cargo' => 'Analista de requerimientos','usuario' => 'Margarita Londoño','ticket' => '10548','centro_costos' => '335 - PROYECTO FABRICA DE SOFTWARE SECRETARÍA DE EDUCACIÓN - SED'],
            ['cargo' => 'Asesor','usuario' => 'Manuel Alexander Cuervo Pacheco','ticket' => '9666','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Agente de contact Center','usuario' => 'Santiago Colorado','ticket' => '10927','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Agente de contact Center','usuario' => 'Luz Milena Gomez ','ticket' => '11034','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asesor','usuario' => 'Jeferson Camilo Jimenez Navarro','ticket' => '9455','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Desarrollador Java','usuario' => 'William Bohorquez Gutierrez','ticket' => '10066','centro_costos' => '318 - PROYECTO FABRICA DE SOFTWARE 2022-FISCALIA'],
            ['cargo' => 'Desarrollador Java Sprintboot','usuario' => 'Yoselin Cecilia Machado Vega','ticket' => '10067','centro_costos' => '318 - PROYECTO FABRICA DE SOFTWARE 2022-FISCALIA'],
            ['cargo' => 'Desarrollador Angular','usuario' => 'Johanna Villalba (Andres Villalba)','ticket' => '10820','centro_costos' => '318 - PROYECTO FABRICA DE SOFTWARE 2022-FISCALIA'],
            ['cargo' => 'DBA','usuario' => 'Guillermo León Prieto Zapata','ticket' => '9505','centro_costos' => 'N/A'],
            ['cargo' => 'Implementador ECM','usuario' => 'Andrés Felipe Velásquez Salazar','ticket' => '9515','centro_costos' => 'N/A'],
            ['cargo' => 'Implementador BUS','usuario' => 'Jarek Leonardo Giraldo Leiva','ticket' => '9516','centro_costos' => 'N/A'],
            ['cargo' => 'Profesional Operativo','usuario' => 'Jorge Eliecer Zuñiga Barros','ticket' => '10259','centro_costos' => '321 - PROYECTO CPE MONITOREO Y EVALUACIÓN FASE II'],
            ['cargo' => 'Realizador Audiovisual','usuario' => 'Sebastian Felipe Fajardo Villareal','ticket' => '9756','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador Sprintboot','usuario' => 'Camilo Rincon','ticket' => '10540','centro_costos' => '318 - PROYECTO FABRICA DE SOFTWARE 2022-FISCALIA'],
            ['cargo' => 'Gestor Documental de Proyectos','usuario' => 'Luz Angela Castro Ortiz','ticket' => '10359','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador java','usuario' => 'Jean Carlos Carrero Roa','ticket' => '11009','centro_costos' => '342- MINMINAS ORFEO'],
            ['cargo' => 'INGENIERO DE REQUERIMIENTOS','usuario' => 'Daniel Ricardo Guerrerro Amaya','ticket' => '10674','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'DESARROLLADOR JAVA','usuario' => 'Juan Diego Manotas Campos','ticket' => '10718','centro_costos' => '303 - PROYECTO 472 CONTRATO N° 239-2021'],
            ['cargo' => 'Desarrollador Intermedio','usuario' => 'Nestor Rafael Barraza Otalvarez','ticket' => '8903','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador Full Stack Java','usuario' => 'Ivan Dario Murcia Moreno','ticket' => '10064','centro_costos' => '318 - PROYECTO FABRICA DE SOFTWARE 2022-FISCALIA'],
            ['cargo' => 'DESARROLLADOR JAVA','usuario' => 'Diego Sanchez','ticket' => '10719','centro_costos' => '303 - PROYECTO 472 CONTRATO N° 239-2021'],
            ['cargo' => 'Desarrollador Java','usuario' => 'John Eddie Diaz Agudelo','ticket' => '10679','centro_costos' => '303 - PROYECTO 472 CONTRATO N° 239-2021'],
            ['cargo' => 'Analista de Aplicaciones','usuario' => 'Jeison Hernan Candamil Mahecha','ticket' => '11338','centro_costos' => 'N/A'],
            ['cargo' => 'DESARROLLADOR PLSQL','usuario' => 'Jesus Cogua','ticket' => '10694','centro_costos' => '318 - PROYECTO FABRICA DE SOFTWARE 2022-FISCALIA'],
            ['cargo' => 'Desarrollador Backend','usuario' => 'Camilo Andres Gil Ballen','ticket' => '11310','centro_costos' => 'N/A'],
            ['cargo' => 'Capacitador y Lider metodología de construcción','usuario' => 'William Forero','ticket' => '8567','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Gerente auditorìa y control interno','usuario' => 'Jorge Andres Medina Galeano','ticket' => 'N/A','centro_costos' => 'N/A'],
            ['cargo' => 'Analista Calidad','usuario' => 'Juan carlos Pinto','ticket' => '9477','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Asesor','usuario' => 'Laura Alexandra Izquierdo Buitrago','ticket' => '9456','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Real time analist','usuario' => 'Luis Antonio Bernal','ticket' => '11032','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'BackOffice','usuario' => 'Vasti Daney Osorio Montoya','ticket' => '10207','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Agente de contact Center','usuario' => 'Lina Peña','ticket' => '11037','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Agente de contact Center','usuario' => 'Laura Marcela Deaza Cerda','ticket' => '11111','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Claudia Milena Toscano Albarracin','ticket' => '9761','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Analista de Calidad ','usuario' => 'Jeferson Alexander Beltrán Barrera','ticket' => '11138','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Lider de Copy y relaciones públicas','usuario' => 'Diana Carolina Sabogal Pulido','ticket' => '6223','centro_costos' => 'N/A'],
            ['cargo' => 'Tutor','usuario' => 'Cristian Felipe Novoa','ticket' => '9762','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Edwin Laverde','ticket' => '9763','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Gina Avila','ticket' => '9764','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Agente','usuario' => 'Laila Brigith Chalarca Aranda','ticket' => '9870','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Luisa Florez','ticket' => '9773','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Laura Yepez','ticket' => '9772','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Maria Gomez','ticket' => '9774','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Nasly Leal','ticket' => '9775','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Zury Gonzalez','ticket' => '9776','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Beatriz Benitez','ticket' => '9777','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Diego Linares','ticket' => '9791','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Adriana Torres','ticket' => '9794','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Andres Orejuela','ticket' => '9795','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Jhonatan Lopez','ticket' => '9792','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Domingo Anichiarico','ticket' => '9799','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Felix Forero','ticket' => '9830','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Elida Silva','ticket' => '9827','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Ivan Romero','ticket' => '9835','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Ivan Vargas','ticket' => '9836','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Jair Lechuga','ticket' => '9837','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Mauricio Castro','ticket' => '9840','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Orlando Calderon','ticket' => '9844','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Yury Toledo','ticket' => '9848','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Saray Cotes','ticket' => '9847','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Dilson Babilonia','ticket' => '9885','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Beatriz Benitez','ticket' => '9777','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'Tutor','usuario' => 'Marleth Lechuga','ticket' => '9887','centro_costos' => '315 - PROYECTO TIENDAS VIRTUALES 3.0 2022'],
            ['cargo' => 'asistente de contratacion','usuario' => 'Cristian Camilo Jimenez Romero','ticket' => '10894','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador Java','usuario' => 'Leyla Cristina Goyeneche Gordillo','ticket' => '10671','centro_costos' => '303 - PROYECTO 472 CONTRATO N° 239-2021'],
            ['cargo' => 'Analista de Proceso (Manuales)','usuario' => 'Jennys Milena Araujo Barreto','ticket' => '11370','centro_costos' => '339- PROLINKTIC'],
            ['cargo' => 'Ingeniero de Infraestructura Cloud','usuario' => 'Cesar Fabian Muñoz Lopez','ticket' => '10883','centro_costos' => 'N/A'],
            ['cargo' => 'Ingenerio DevOps','usuario' => 'Cristhian Danilo Jimenez Pardo','ticket' => '10284','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador Frontend','usuario' => 'Dixon Anato Ascencio','ticket' => '11307','centro_costos' => 'N/A'],
            ['cargo' => 'Scrum Master','usuario' => 'Gynna Maria Rodriguez Gomez','ticket' => '8062','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador Orfeo','usuario' => 'Carlos Alberto Barrero Cantor','ticket' => '11212','centro_costos' => '324 - PROYECTO ADRES'],
            ['cargo' => 'Desarrollador fullstack','usuario' => 'Heiner Santiago Alfonso Casallas','ticket' => '11379','centro_costos' => '349 - FABRICA DE SOFTWARE - SUPERFINANCIERA'],
            ['cargo' => 'Analista de requerimientos','usuario' => 'Camilo Andres Ramirez Obando','ticket' => '10154','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Desarrollador Back-End','usuario' => 'Edsson Orlando Pedreros Sastoque','ticket' => '10263','centro_costos' => 'N/A'],
            ['cargo' => 'Experto en digitalizacion y migracion de datos','usuario' => 'Jaime Andres Guevara Gavarito','ticket' => '11190','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Diseñador Grafico','usuario' => 'Luisa Fernanda Bedoya Castillo','ticket' => '9946','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador Java','usuario' => 'Jaime Alberto Gutierrez Mejia','ticket' => '11010','centro_costos' => '342- MINMINAS ORFEO'],
            ['cargo' => 'Desarrollador PHP orfeo','usuario' => 'Juan David Parroquiano Vargas','ticket' => '11193','centro_costos' => '342- MINMINAS ORFEO'],
            ['cargo' => 'Desarrollador Orfeo','usuario' => 'Johnnatan Rodriguez Pinto','ticket' => '11213','centro_costos' => '324 - PROYECTO ADRES'],
            ['cargo' => 'Auditor  ','usuario' => 'Luis Alberto Villarreal Otiveros','ticket' => '7836','centro_costos' => 'N/A'],
            ['cargo' => 'Desarrollador ORFEO','usuario' => 'Jorge Enrique Lopéz Timaná','ticket' => '11442','centro_costos' => '324 - PROYECTO ADRES'],
            ['cargo' => 'Ingeniero de infraestructura senior','usuario' => 'William Quintero Torres','ticket' => '11559','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],
            ['cargo' => 'Ing preventa Sr','usuario' => 'Julian Andres Garcia Maca','ticket' => '10937','centro_costos' => 'N/A'],
            ['cargo' => 'Analista Funcional','usuario' => 'Dora Mignely Ambuila Tovar','ticket' => '11169','centro_costos' => '348 - SGDEA ACUEDUCTO'],
            ['cargo' => 'Ingeniero de infraestructura','usuario' => 'Alvaro Nuñez','ticket' => '11289','centro_costos' => '291 - PROYECTO RAMA JUDICIAL'],

        ];
        foreach ($retiros as $item) {
            DB::table('retiros')->insert([
                'cargo' => $item['cargo'],
                'usuario' => $item['usuario'],
                'ticket' => $item['ticket'],
                'centro_costos' => $item['centro_costos'],
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ]);
        }
    }
}
