<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Tabla_Cargo extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cargos = [
            ['area_id' => '14', 'cargo' => 'Abogado'],
            ['area_id' => '14', 'cargo' => 'Abogado Civil'],
            ['area_id' => '14', 'cargo' => 'Abogado De Familia'],
            ['area_id' => '14', 'cargo' => 'Abogado Funcional'],
            ['area_id' => '14', 'cargo' => 'Abogado Penalista'],
            ['area_id' => '14', 'cargo' => 'Administrador De Moodle'],
            ['area_id' => '14', 'cargo' => 'Agente Backoffice Calidad'],
            ['area_id' => '14', 'cargo' => 'Agente De Backoffice'],
            ['area_id' => '13', 'cargo' => 'Agente De Soporte Tecnico'],
            ['area_id' => '14', 'cargo' => 'Agente Ventas'],
            ['area_id' => '2','cargo' => 'Analista Contable'],
            ['area_id' => '13', 'cargo' => 'Analista De Aplicaciones'],
            ['area_id' => '14', 'cargo' => 'Analista De Automatizacion'],
            ['area_id' => '12','cargo' => 'Analista De Automatización De Marketing'],
            ['area_id' => '13','cargo' => 'Analista De Calidad'],
            ['area_id' => '7', 'cargo' => 'Analista De Contratacion Publica'],
            ['area_id' => '12', 'cargo' => 'Analista De Marketing'],
            ['area_id' => '13', 'cargo' => 'Analista De Migracion Y Datos'],
            ['area_id' => '13', 'cargo' => 'Analista De Migración Y Datos'],
            ['area_id' => '2', 'cargo' => 'Analista De Nomina'],
            ['area_id' => '12', 'cargo' => 'Analista De Pauta'],
            ['area_id' => '15', 'cargo' => 'Analista De Planeación Financiera'],
            ['area_id' => '13', 'cargo' => 'Analista De Proceso (Manuales)'],
            ['area_id' => '14', 'cargo' => 'Analista De Procesos'],
            ['area_id' => '13', 'cargo' => 'Analista De Procesos Erp'],
            ['area_id' => '15', 'cargo' => 'Analista De Proyectos'],
            ['area_id' => '14','cargo' => 'Analista De Proyectos'],
            ['area_id' => '13', 'cargo' => 'Analista De Pruebas'],
            ['area_id' => '13', 'cargo' => 'Analista De Pruebas Junior'],
            ['area_id' => '13', 'cargo' => 'Analista De Pruebas Senior'],
            ['area_id' => '13', 'cargo' => 'Analista De Requerimiento'],
            ['area_id' => '13', 'cargo' => 'Analista De Requerimientos'],
            ['area_id' => '13','cargo' => 'Analista De Requerimientos Y Prueba'],
            ['area_id' => '13', 'cargo' => 'Analista De Requerimientos Y Qa'],
            ['area_id' => '14', 'cargo' => 'Analista De Seleccion'],
            ['area_id' => '14', 'cargo' => 'Analista De Seleccion Senior'],
            ['area_id' => '13', 'cargo' => 'Analista De Sistemas'],
            ['area_id' => '13', 'cargo' => 'Analista De Soporte'],
            ['area_id' => '13', 'cargo' => 'Analista Documentador'],
            ['area_id' => '14', 'cargo' => 'Analista En Gestión Documental'],
            ['area_id' => '15', 'cargo' => 'Analista Financiero'],
            ['area_id' => '13','cargo' =>'Analista Funcional De Requerimiento Y Aseguramiento De La Calidad'],
            ['area_id' => '14', 'cargo' => 'Analista Mesa De Ayuda'],
            ['area_id' => '13', 'cargo' => 'Analista Migración'],
            ['area_id' => '14', 'cargo' => 'Analista Pmo'],
            ['area_id' => '13', 'cargo' => 'Analista Qa'],
            ['area_id' => '13', 'cargo' => 'Analista Senior De Requerimientos'],
            ['area_id' => '12', 'cargo' => 'Analista Soporte Marketing'],
            ['area_id' => '13', 'cargo' => 'Analista Y Desarrollador Abap'],
            ['area_id' => '6', 'cargo' => 'Aprendiz Sena'],
            ['area_id' => '13', 'cargo' => 'Arquitecta De Datos'],
            ['area_id' => '14', 'cargo' => 'Arquitecto De Aplicaciones'],
            ['area_id' => '13', 'cargo' => 'Arquitecto De Software'],
            ['area_id' => '13', 'cargo' => 'Arquitecto De Soluciones'],
            ['area_id' => '14', 'cargo' => 'Asesor'],
            ['area_id' => '2', 'cargo' => 'Asesor Financiero'],
            ['area_id' => '14','cargo' => 'Asesor Jurídico - Esp. Administrativa'],
            ['area_id' => '2', 'cargo' => 'Asistente Administrativo'],
            ['area_id' => '7', 'cargo' => 'Asistente De Contratacion'],
            ['area_id' => '14', 'cargo' => 'Asistente De Contratación'],
            ['area_id' => '6', 'cargo' => 'Asistente De Diseño'],
            ['area_id' => '11', 'cargo' => 'Asistente De Gerencia'],
            ['area_id' => '14','cargo' => 'Asistente De Recreación Y Bienestar-Aprendiz Sena'],
            ['area_id' => '13', 'cargo' => 'Asistente De Soporte'],
            ['area_id' => '14','cargo' => 'Asistente De Soporte Y Requerimientos'],
            ['area_id' => '14', 'cargo' => 'Asistente De Talento Humano'],
            ['area_id' => '2','cargo' => 'Asistente Financiera, Tesorera'],
            ['area_id' => '14', 'cargo' => 'Auditor'],
            ['area_id' => '2', 'cargo' => 'Auxiliar Administrativa'],
            ['area_id' => '2', 'cargo' => 'Auxiliar Contable'],
            ['area_id' => '12', 'cargo' => 'Auxiliar De Diseño'],
            ['area_id' => '13', 'cargo' => 'Backend De Marketing'],
            ['area_id' => '12', 'cargo' => 'Community Manager'],
            ['area_id' => '6', 'cargo' => 'Consultor De Comunicaciones'],
            ['area_id' => '14', 'cargo' => 'Consultor De Talento Humano'],
            ['area_id' => '14', 'cargo' => 'Coordinador De Calidad'],
            ['area_id' => '12','cargo' => 'Coordinador De Marketing'],
            ['area_id' => '14', 'cargo' => 'Coordinador De Proyectos'],
            ['area_id' => '13', 'cargo' => 'Coordinador Tecnico'],
            ['area_id' => '13', 'cargo' => 'Coordinadora De Servicos Ti'],
            ['area_id' => '14', 'cargo' => 'Coordinadora Operativa'],
            ['area_id' => '6', 'cargo' => 'Copy Junior'],
            ['area_id' => '12', 'cargo' => 'Copywriter'],
            ['area_id' => '12', 'cargo' => 'Data Science'],
            ['area_id' => '14', 'cargo' => 'Datamarshall'],
            ['area_id' => '13', 'cargo' => 'Desarollador Junior'],
            ['area_id' => '13', 'cargo' => 'Desarrolador Bpm'],
            ['area_id' => '12', 'cargo' => 'Desarrolador Fullstack'],
            ['area_id' => '13', 'cargo' => 'Desarrollador'],
            ['area_id' => '13', 'cargo' => 'Desarrollador .Net'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Angular'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Backend'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Back-End'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Bi Intermedio'],
            ['area_id' => '13', 'cargo' => 'Desarrollador De Orfeo'],
            ['area_id' => '12', 'cargo' => 'Desarrollador De Wordpress'],
            ['area_id' => '12', 'cargo' => 'Desarrollador Front'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Front End'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Frontend'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Front-End'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Full Stack Java'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Fullstack'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Intermedio'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Java'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Java Junior'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Java Senior'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Java Sprintboot'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Junior'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Node Js'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Nodejs-React'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Orfeo'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Php Orfeo'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Php-Orfeo'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Python'],
            ['area_id' => '13', 'cargo' => 'Desarrollador React'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Senior'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Senior En Php'],
            ['area_id' => '13', 'cargo' => 'Desarrollador Sprintboot'],
            ['area_id' => '12', 'cargo' => 'Desarrollador Wordpress'],
            ['area_id' => '13', 'cargo' => 'Desarrolladora .Net'],
            ['area_id' => '13', 'cargo' => 'Desarrolladora Backend'],
            ['area_id' => '13', 'cargo' => 'Desarrolladora Front'],
            ['area_id' => '13', 'cargo' => 'Desarrolladora Java Senior'],
            ['area_id' => '14','cargo' =>'Desarrolladora Y Apoyo En Construcción De Contenidos Capacitación'],
            ['area_id' => '3', 'cargo' => 'Director Comercial'],
            ['area_id' => '2','cargo' => 'Directora Administrativa Y Financiera'],
            ['area_id' => '14', 'cargo' => 'Directora Juridica'],
            ['area_id' => '12', 'cargo' => 'Diseñador'],
            ['area_id' => '12', 'cargo' => 'Diseñador De Contenidos'],
            ['area_id' => '12', 'cargo' => 'Diseñador Gráfico'],
            ['area_id' => '13', 'cargo' => 'Diseñador Ux'],
            ['area_id' => '12', 'cargo' => 'Diseñadora'],
            ['area_id' => '12', 'cargo' => 'Diseñadora De Interfaces'],
            ['area_id' => '6', 'cargo' => 'Diseñadora Digital'],
            ['area_id' => '12', 'cargo' => 'Diseñadora Grafica'],
            ['area_id' => '14', 'cargo' => 'Documentador'],
            ['area_id' => '13', 'cargo' => 'Documentador 1'],
            ['area_id' => '13', 'cargo' => 'Documentador 2'],
            ['area_id' => '14','cargo' => 'Especialista En Gestión Documental'],
            ['area_id' => '13','cargo' => 'Especialista En Migración De Datos 1'],
            ['area_id' => '13','cargo' => 'Experto En Digitalizacion Y Migracion'],
            ['area_id' => '13','cargo' => 'Experto En Digitalizacion Y Migracion De Datos'],
            ['area_id' => '4', 'cargo' => 'Gerente De Auditoria'],
            ['area_id' => '13', 'cargo' => 'Gerente De Calidad'],
            ['area_id' => '6', 'cargo' => 'Gerente De Comunicaciones.'],
            ['area_id' => '7', 'cargo' => 'Gerente De Contratación Pública'],
            ['area_id' => '14', 'cargo' => 'Gerente De La Pmo'],
            ['area_id' => '12', 'cargo' => 'Gerente De Marketing.'],
            ['area_id' => '11', 'cargo' => 'Gerente De Operaciones'],
            ['area_id' => '14', 'cargo' => 'Gerente De Proyecto'],
            ['area_id' => '14', 'cargo' => 'Gerente De Proyectos'],
            ['area_id' => '11', 'cargo' => 'Gerente General'],
            ['area_id' => '13','cargo' => 'Gestor De Requerimientos'],
            ['area_id' => '13', 'cargo' => 'Gestor Documental De Proyectos'],
            ['area_id' => '7', 'cargo' => 'Ing Preventa Sr'],
            ['area_id' => '13', 'cargo' => 'Ingenerio Devops'],
            ['area_id' => '14', 'cargo' => 'Ingeniero'],
            ['area_id' => '13', 'cargo' => 'Ingeniero (Synaptica)'],
            ['area_id' => '13', 'cargo' => 'Ingeniero De Infraestructura Cloud'],
            ['area_id' => '13', 'cargo' => 'Ingeniero De Requerimeintos'],
            ['area_id' => '13', 'cargo' => 'Ingeniero De Requerimientos'],
            ['area_id' => '13','cargo' => 'Ingeniero De Requerimientos Y Scrum Master'],
            ['area_id' => '13', 'cargo' => 'Ingeniero Desarrollo Intermedio'],
            ['area_id' => '13', 'cargo' => 'Ingeniero Devops'],
            ['area_id' => '7', 'cargo' => 'Ingeniero Preventa Junior'],
            ['area_id' => '14', 'cargo' => 'Jefe De Operaciones Call Center'],
            ['area_id' => '6', 'cargo' => 'Lider Copy'],
            ['area_id' => '13', 'cargo' => 'Lider De Arquitectura'],
            ['area_id' => '12', 'cargo' => 'Lider De Diseño'],
            ['area_id' => '14', 'cargo' => 'Lider De Formación'],
            ['area_id' => '14','cargo' => 'Lider De Gestión Documental'],
            ['area_id' => '13', 'cargo' => 'Lider De Implementación'],
            ['area_id' => '13', 'cargo' => 'Lider De Infraestructura'],
            ['area_id' => '13', 'cargo' => 'Lider De Metodologias Agiles'],
            ['area_id' => '13','cargo' => 'Líder De Migración Y Apoyo En Analítica De Datos'],
            ['area_id' => '13', 'cargo' => 'Lider De Pruebas'],
            ['area_id' => '13','cargo' => 'Líder De Pruebas'],
            ['area_id' => '13', 'cargo' => 'Lider De Requerimientos'],
            ['area_id' => '13','cargo' => 'Lìder De Seguridad De La Informaciòn'],
            ['area_id' => '13', 'cargo' => 'Lider De Soporte'],
            ['area_id' => '13', 'cargo' => 'Lider De Tecnologia'],
            ['area_id' => '15', 'cargo' => 'Líder Financiero'],
            ['area_id' => '13', 'cargo' => 'Lider Noc/Soc'],
            ['area_id' => '14', 'cargo' => 'Líder Talento Humano'],
            ['area_id' => '13', 'cargo' => 'Lider Tecnico'],
            ['area_id' => '13', 'cargo' => 'Líder Técnico'],
            ['area_id' => '12', 'cargo' => 'Maquetador Junior'],
            ['area_id' => '12','cargo' => 'Planner Estrategico'],
            ['area_id' => '6', 'cargo' => 'Posproductor'],
            ['area_id' => '12', 'cargo' => 'Practicante De Marketing'],
            ['area_id' => '11', 'cargo' => 'Profesional Administrativo'],
            ['area_id' => '14','cargo' => 'Profesional De Apoyo Programa Primer Empleo'],
            ['area_id' => '4','cargo' => 'Profesional De Auditoria De Procesos'],
            ['area_id' => '7','cargo' => 'Profesional De Contratacion Publica'],
            ['area_id' => '12', 'cargo' => 'Profesional De Marketing'],
            ['area_id' => '1', 'cargo' => 'Profesional De Operaciones'],
            ['area_id' => '14', 'cargo' => 'Profesional De Seleccion'],
            ['area_id' => '14', 'cargo' => 'Profesional En Seleccion'],
            ['area_id' => '6','cargo' => 'Profesional Especializado En Cominicaciones.'],
            ['area_id' => '14', 'cargo' => 'Profesional Especializado Pmo'],
            ['area_id' => '14', 'cargo' => 'Profesional Juridico'],
            ['area_id' => '14', 'cargo' => 'Profesional Operativo'],
            ['area_id' => '14', 'cargo' => 'Profesional Pmo'],
            ['area_id' => '13', 'cargo' => 'Profesional Tecnico Bpm'],
            ['area_id' => '13', 'cargo' => 'Profesional Técnico Bpm'],
            ['area_id' => '6', 'cargo' => 'Realizador Audiovisual'],
            ['area_id' => '12', 'cargo' => 'Realizador Audiovisual Campo'],
            ['area_id' => '2', 'cargo' => 'Revisora Fiscal'],
            ['area_id' => '13', 'cargo' => 'Scrum Master'],
            ['area_id' => '14','cargo' => 'Servicios De Comunicacion Y Temas Legales'],
            ['area_id' => '13', 'cargo' => 'Soporte'],
            ['area_id' => '14','cargo' =>'Tecnólogo En Análisis Y Desarrollo De Sistemas De Información'],
            ['area_id' => '12', 'cargo' => 'Traffic Manager'],
        ];
        foreach ($cargos as $key => $value) {
            DB::table('cargos')->insert([
                'area_id' => $value['area_id'],
                'cargo' => $value['cargo'],
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ]);
        }
    }
}
