<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Tabla_Cargo extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cargos = [
            ['area_id' => '4', 'cargo' => 'Abogada'],
            ['area_id' => '4', 'cargo' => 'Abogada Funcional'],
            ['area_id' => '4', 'cargo' => 'Abogado Civil'],
            ['area_id' => '4', 'cargo' => 'Abogado de Familia'],
            ['area_id' => '4', 'cargo' => 'Abogado Funcional'],
            ['area_id' => '4', 'cargo' => 'Abogado Penalista'],
            ['area_id' => '4', 'cargo' => 'Administrador de moodle'],
            ['area_id' => '4', 'cargo' => 'Agente backoffice calidad'],
            ['area_id' => '4', 'cargo' => 'Agente de BackOffice'],
            ['area_id' => '3', 'cargo' => 'Agente de Soporte Tecnico'],
            ['area_id' => '4', 'cargo' => 'Agente ventas'],
            ['area_id' => '3','cargo' => 'Analista Contable'],
            ['area_id' => '4', 'cargo' => 'Analista de Aplicaciones'],
            ['area_id' => '4', 'cargo' => 'Analista de Automatizacion'],
            ['area_id' => '3','cargo' => 'analista de automatización de marketing'],
            ['area_id' => '4','cargo' => 'Analista de Calidad'],
            ['area_id' => '3', 'cargo' => 'Analista de contratacion publica'],
            ['area_id' => '3', 'cargo' => 'Analista de Marketing'],
            ['area_id' => '3', 'cargo' => 'Analista de Migracion y datos'],
            ['area_id' => '3', 'cargo' => 'ANALISTA DE MIGRACIÓN Y DATOS'],
            ['area_id' => '3', 'cargo' => 'Analista de Nomina'],
            ['area_id' => '3', 'cargo' => 'Analista de Pauta'],
            ['area_id' => '5', 'cargo' => 'Analista de Planeación Financiera'],
            ['area_id' => '3', 'cargo' => 'Analista de Proceso (Manuales)'],
            ['area_id' => '7', 'cargo' => 'ANALISTA DE PROCESOS'],
            ['area_id' => '3', 'cargo' => 'ANALISTA DE PROCESOS ERP'],
            ['area_id' => '5', 'cargo' => 'Analista de proyectos'],
            ['area_id' => '4','cargo' => 'Analista de Proyectos'],
            ['area_id' => '3', 'cargo' => 'Analista de pruebas'],
            ['area_id' => '3', 'cargo' => 'Analista de pruebas Junior'],
            ['area_id' => '3', 'cargo' => 'Analista de pruebas Senior'],
            ['area_id' => '3', 'cargo' => 'ANALISTA DE REQUERIMIENTO'],
            ['area_id' => '3', 'cargo' => 'Analista de requerimientos'],
            ['area_id' => '3','cargo' => 'Analista de requerimientos y Prueba'],
            ['area_id' => '3', 'cargo' => 'Analista de Requerimientos y QA'],
            ['area_id' => '4', 'cargo' => 'Analista de seleccion'],
            ['area_id' => '4', 'cargo' => 'Analista de Seleccion Senior'],
            ['area_id' => '3', 'cargo' => 'Analista de sistemas'],
            ['area_id' => '3', 'cargo' => 'Analista de Soporte'],
            ['area_id' => '4', 'cargo' => 'Analista Documentador'],
            ['area_id' => '4', 'cargo' => 'Analista en Gestión Documental'],
            ['area_id' => '5', 'cargo' => 'Analista Financiero'],
            ['area_id' => '3','cargo' =>'Analista funcional de requerimiento y aseguramiento de la calidad'],
            ['area_id' => '4', 'cargo' => 'Analista mesa de ayuda'],
            ['area_id' => '3', 'cargo' => 'Analista Migración'],
            ['area_id' => '7', 'cargo' => 'Analista Noc/Soc'],
            ['area_id' => '4', 'cargo' => 'ANALISTA PMO'],
            ['area_id' => '3', 'cargo' => 'Analista QA'],
            ['area_id' => '3', 'cargo' => 'Analista Senior de Requerimientos'],
            ['area_id' => '3', 'cargo' => 'Analista soporte Marketing'],
            ['area_id' => '3', 'cargo' => 'Analista y desarrollador ABAP'],
            ['area_id' => '3', 'cargo' => 'Aprendiz Sena'],
            ['area_id' => '3', 'cargo' => 'Arquitecta de Datos'],
            ['area_id' => '4', 'cargo' => 'Arquitecto de Aplicaciones'],
            ['area_id' => '3', 'cargo' => 'Arquitecto de Software'],
            ['area_id' => '3', 'cargo' => 'Arquitecto de soluciones'],
            ['area_id' => '4', 'cargo' => 'Asesor'],
            ['area_id' => '3', 'cargo' => 'Asesor Financiero'],
            ['area_id' => '4','cargo' => 'Asesor Jurídico - Esp. Administrativa'],
            ['area_id' => '3', 'cargo' => 'Asistente administrativo'],
            ['area_id' => '3', 'cargo' => 'asistente de contratacion'],
            ['area_id' => '4', 'cargo' => 'Asistente de contratación'],
            ['area_id' => '3', 'cargo' => 'Asistente de Diseño'],
            ['area_id' => '3', 'cargo' => 'Asistente de gerencia'],
            ['area_id' => '4','cargo' => 'Asistente de recreación y bienestar-Aprendiz SENA'],
            ['area_id' => '4', 'cargo' => 'Asistente de Soporte'],
            ['area_id' => '4','cargo' => 'asistente de soporte y requerimientos'],
            ['area_id' => '4', 'cargo' => 'Asistente de Talento Humano'],
            ['area_id' => '3','cargo' => 'Asistente Financiera, tesorera'],
            ['area_id' => '4', 'cargo' => 'Asistente Talento Humano'],
            ['area_id' => '4', 'cargo' => 'Auditor'],
            ['area_id' => '3', 'cargo' => 'AUXILIAR ADMINISTRATIVA'],
            ['area_id' => '3', 'cargo' => 'Auxiliar Contable'],
            ['area_id' => '3', 'cargo' => 'Auxiliar de Diseño'],
            ['area_id' => '3', 'cargo' => 'backend de marketing'],
            ['area_id' => '3', 'cargo' => 'Community Manager'],
            ['area_id' => '3', 'cargo' => 'Consultor de Comunicaciones'],
            ['area_id' => '4', 'cargo' => 'Consultor de Talento Humano'],
            ['area_id' => '4', 'cargo' => 'Coordinador de Calidad'],
            ['area_id' => '3','cargo' => 'Coordinador de Marketing'],
            ['area_id' => '4', 'cargo' => 'Coordinador de Proyectos'],
            ['area_id' => '3', 'cargo' => 'Coordinador Tecnico'],
            ['area_id' => '3', 'cargo' => 'COORDINADORA DE SERVICOS TI'],
            ['area_id' => '4', 'cargo' => 'Coordinadora Operativa'],
            ['area_id' => '3', 'cargo' => 'Copy junior'],
            ['area_id' => '3', 'cargo' => 'Copywriter'],
            ['area_id' => '3', 'cargo' => 'data science'],
            ['area_id' => '4', 'cargo' => 'Datamarshall'],
            ['area_id' => '3', 'cargo' => 'Desarollador Junior'],
            ['area_id' => '3', 'cargo' => 'Desarrolador BPM'],
            ['area_id' => '3', 'cargo' => 'Desarrolador Fullstack'],
            ['area_id' => '3', 'cargo' => 'Desarrollador'],
            ['area_id' => '3', 'cargo' => 'Desarrollador .net'],
            ['area_id' => '3', 'cargo' => 'Desarrollador Angular'],
            ['area_id' => '3', 'cargo' => 'Desarrollador Backend'],
            ['area_id' => '3', 'cargo' => 'DESARROLLADOR BACK-END'],
            ['area_id' => '3', 'cargo' => 'Desarrollador BI intermedio'],
            ['area_id' => '3', 'cargo' => 'Desarrollador de Orfeo'],
            ['area_id' => '3', 'cargo' => 'Desarrollador de WordPress'],
            ['area_id' => '3', 'cargo' => 'Desarrollador Front'],
            ['area_id' => '3', 'cargo' => 'DESARROLLADOR FRONT END'],
            ['area_id' => '3', 'cargo' => 'Desarrollador Frontend'],
            ['area_id' => '3', 'cargo' => 'Desarrollador Front-end'],
            ['area_id' => '3', 'cargo' => 'Desarrollador Full Stack Java'],
            ['area_id' => '3', 'cargo' => 'Desarrollador Fullstack'],
            ['area_id' => '3', 'cargo' => 'Desarrollador intermedio'],
            ['area_id' => '3', 'cargo' => 'Desarrollador Java'],
            ['area_id' => '3', 'cargo' => 'Desarrollador Java Junior'],
            ['area_id' => '3', 'cargo' => 'DESARROLLADOR JAVA SENIOR'],
            ['area_id' => '3', 'cargo' => 'Desarrollador Java Sprintboot'],
            ['area_id' => '3', 'cargo' => 'Desarrollador Junior'],
            ['area_id' => '3', 'cargo' => 'DESARROLLADOR NODE JS'],
            ['area_id' => '3', 'cargo' => 'Desarrollador NODEjs-React'],
            ['area_id' => '3', 'cargo' => 'Desarrollador Orfeo'],
            ['area_id' => '7', 'cargo' => 'Desarrollador PHP'],
            ['area_id' => '3', 'cargo' => 'Desarrollador PHP ORFEO'],
            ['area_id' => '3', 'cargo' => 'Desarrollador PHP-Orfeo'],
            ['area_id' => '3', 'cargo' => 'Desarrollador Python'],
            ['area_id' => '3', 'cargo' => 'Desarrollador React'],
            ['area_id' => '3', 'cargo' => 'Desarrollador senior'],
            ['area_id' => '3', 'cargo' => 'DESARROLLADOR SENIOR EN PHP'],
            ['area_id' => '3', 'cargo' => 'Desarrollador Sprintboot'],
            ['area_id' => '3', 'cargo' => 'Desarrollador wordpress'],
            ['area_id' => '3', 'cargo' => 'Desarrolladora .net'],
            ['area_id' => '3', 'cargo' => 'Desarrolladora Backend'],
            ['area_id' => '3', 'cargo' => 'Desarrolladora Front'],
            ['area_id' => '3', 'cargo' => 'Desarrolladora Java Senior'],
            ['area_id' => '4','cargo' =>'Desarrolladora y apoyo en construcción de contenidos Capacitación'],
            ['area_id' => '3', 'cargo' => 'Director Comercial'],
            ['area_id' => '3','cargo' => 'Directora Administrativa y Financiera'],
            ['area_id' => '4', 'cargo' => 'Directora Juridica'],
            ['area_id' => '3', 'cargo' => 'Diseñador'],
            ['area_id' => '3', 'cargo' => 'Diseñador de contenidos'],
            ['area_id' => '3', 'cargo' => 'Diseñador grafico'],
            ['area_id' => '3', 'cargo' => 'Diseñador gráfico'],
            ['area_id' => '7', 'cargo' => 'Diseñador Gráfico audiovisual'],
            ['area_id' => '3', 'cargo' => 'DISEÑADOR UX'],
            ['area_id' => '3', 'cargo' => 'Diseñadora'],
            ['area_id' => '3', 'cargo' => 'Diseñadora de interfaces'],
            ['area_id' => '3', 'cargo' => 'Diseñadora Digital'],
            ['area_id' => '3', 'cargo' => 'Diseñadora Grafica'],
            ['area_id' => '3','cargo' => 'Diseñadora grafica'],
            ['area_id' => '4', 'cargo' => 'Documentador'],
            ['area_id' => '3', 'cargo' => 'Documentador 1'],
            ['area_id' => '3', 'cargo' => 'Documentador 2'],
            ['area_id' => '4', 'cargo' => 'Especialista en gestión documental'],
            ['area_id' => '4','cargo' => 'Especialista en gestión documental'],
            ['area_id' => '3','cargo' => 'Especialista en Migración de datos 1'],
            ['area_id' => '3','cargo' => 'Experto en digitalizacion y migracion'],
            ['area_id' => '3','cargo' => 'Experto en digitalizacion y migracion de datos'],
            ['area_id' => '3', 'cargo' => 'Gerente de Auditoria'],
            ['area_id' => '4', 'cargo' => 'Gerente de Calidad'],
            ['area_id' => '3', 'cargo' => 'Gerente de Comunicaciones.'],
            ['area_id' => '3', 'cargo' => 'Gerente de Contratación Pública'],
            ['area_id' => '4', 'cargo' => 'Gerente de la PMO'],
            ['area_id' => '3', 'cargo' => 'Gerente de Marketing.'],
            ['area_id' => '3', 'cargo' => 'Gerente de Operaciones'],
            ['area_id' => '4', 'cargo' => 'Gerente de proyecto'],
            ['area_id' => '4', 'cargo' => 'Gerente de Proyectos'],
            ['area_id' => '3', 'cargo' => 'Gerente fabrica de software'],
            ['area_id' => '3', 'cargo' => 'Gerente General'],
            ['area_id' => '7', 'cargo' => 'Gerente Juridico'],
            ['area_id' => '3','cargo' => 'Gestor de requerimientos'],
            ['area_id' => '3', 'cargo' => 'Gestor Documental de Proyectos'],
            ['area_id' => '3', 'cargo' => 'Ing preventa Sr'],
            ['area_id' => '3', 'cargo' => 'Ingenerio DevOps'],
            ['area_id' => '4', 'cargo' => 'Ingeniero'],
            ['area_id' => '3', 'cargo' => 'Ingeniero (Synaptica)'],
            ['area_id' => '3', 'cargo' => 'Ingeniero de Infraestructura Cloud'],
            ['area_id' => '3', 'cargo' => 'Ingeniero de Requerimeintos'],
            ['area_id' => '3', 'cargo' => 'Ingeniero de requerimientos'],
            ['area_id' => '3','cargo' => 'Ingeniero de requerimientos y scrum master'],
            ['area_id' => '3', 'cargo' => 'Ingeniero desarrollo intermedio'],
            ['area_id' => '3', 'cargo' => 'Ingeniero DevOps'],
            ['area_id' => '3', 'cargo' => 'INGENIERO PREVENTA JUNIOR'],
            ['area_id' => '4', 'cargo' => 'Jefe de Operaciones Call Center'],
            ['area_id' => '3', 'cargo' => 'Lider Comercial'],
            ['area_id' => '3', 'cargo' => 'Lider Copy'],
            ['area_id' => '3', 'cargo' => 'Lider de arquitectura'],
            ['area_id' => '3', 'cargo' => 'Lider de diseño'],
            ['area_id' => '4', 'cargo' => 'Lider de Formación'],
            ['area_id' => '4','cargo' => 'Lider de Gestión Documental'],
            ['area_id' => '3', 'cargo' => 'Lider de Implementación'],
            ['area_id' => '3', 'cargo' => 'Lider de Infraestructura'],
            ['area_id' => '3', 'cargo' => 'Lider de Metodologias Agiles'],
            ['area_id' => '3','cargo' => 'Líder de Migración y apoyo en analítica de datos'],
            ['area_id' => '3', 'cargo' => 'Lider de pruebas'],
            ['area_id' => '3','cargo' => 'Líder de pruebas'],
            ['area_id' => '3', 'cargo' => 'Lider de Requerimientos'],
            ['area_id' => '3','cargo' => 'Lìder de seguridad de la informaciòn'],
            ['area_id' => '4', 'cargo' => 'Lider de Soporte'],
            ['area_id' => '3', 'cargo' => 'Lider de Tecnologia'],
            ['area_id' => '5', 'cargo' => 'Líder Financiero'],
            ['area_id' => '3', 'cargo' => 'Lider NOC/SOC'],
            ['area_id' => '7', 'cargo' => 'Lider preventa'],
            ['area_id' => '4', 'cargo' => 'Líder Talento Humano'],
            ['area_id' => '3', 'cargo' => 'Lider Tecnico'],
            ['area_id' => '3', 'cargo' => 'líder técnico'],
            ['area_id' => '3', 'cargo' => 'Maquetador Junior'],
            ['area_id' => '3','cargo' => 'Planner estrategico'],
            ['area_id' => '3', 'cargo' => 'posproductor'],
            ['area_id' => '3', 'cargo' => 'Practicante de marketing'],
            ['area_id' => '3', 'cargo' => 'Profesional Administrativo'],
            ['area_id' => '4','cargo' => 'Profesional de apoyo Programa primer empleo'],
            ['area_id' => '3','cargo' => 'Profesional de Auditoria de Procesos'],
            ['area_id' => '3','cargo' => 'Profesional de Contratacion Publica'],
            ['area_id' => '3', 'cargo' => 'Profesional de marketing'],
            ['area_id' => '4', 'cargo' => 'Profesional de seleccion'],
            ['area_id' => '4', 'cargo' => 'Profesional en seleccion'],
            ['area_id' => '3','cargo' => 'Profesional especializado en cominicaciones'],
            ['area_id' => '4', 'cargo' => 'Profesional Especializado PMO'],
            ['area_id' => '4', 'cargo' => 'Profesional Juridico'],
            ['area_id' => '4', 'cargo' => 'Profesional Operativo'],
            ['area_id' => '4', 'cargo' => 'Profesional PMO'],
            ['area_id' => '3', 'cargo' => 'Profesional tecnico BPM'],
            ['area_id' => '3', 'cargo' => 'Profesional Técnico BPM'],
            ['area_id' => '3', 'cargo' => 'Realizador Audiovisual'],
            ['area_id' => '3', 'cargo' => 'realizador audiovisual campo'],
            ['area_id' => '3', 'cargo' => 'Revisora Fiscal'],
            ['area_id' => '3', 'cargo' => 'Scrum Master'],
            ['area_id' => '4','cargo' => 'servicios de comunicacion y temas legales'],
            ['area_id' => '3', 'cargo' => 'Soporte'],
            ['area_id' => '4','cargo' =>'Tecnólogo en análisis y desarrollo de sistemas de información'],
            ['area_id' => '3', 'cargo' => 'Traffic Manager'],
        ];
        foreach ($cargos as $key => $value) {
            DB::table('cargos')->insert([
                'area_id' => $value['area_id'],
                'cargo' => $value['cargo'],
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ]);
        }
    }
}
